In [1]:
import pandas as pd
import yfinance as yf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
import json

In [2]:
exog_columns = {}

# Economics

### External Covariates: Financial Markets (Brent Crude Oil)

#### 1. What is "Brent" and what are its units?
**Brent Crude Oil** is the major trading classification of sweet light crude oil that serves as a major benchmark price for purchases of oil worldwide, particularly in Europe.
* **What it represents:** The price of a futures contract for oil delivery.
* **Unit of measurement:** US Dollars (USD) per barrel.
*(Note: Since oil is traded in USD and the Spanish economy operates in EUR, the real industrial impact depends on the combination of both. This justifies our later inclusion of the EUR/USD exchange rate).*

#### 2. What do Open, High, Low, and Close mean?
Financial markets are not open 24/7. Throughout the trading session, prices fluctuate. Financial datasets summarize this daily activity using four key data points (OHLC):
* **Open:** The price of the first trade when the market opens.
* **High:** The highest price the asset reached during the trading day.
* **Low:** The lowest price the asset reached during the trading day.
* **Close:** The final price at which the asset traded before the market closed.

#### 3. Why do we keep ONLY the "Close" column?
We drop the Open, High, and Low columns for two fundamental technical reasons regarding our Machine Learning model:
1.  **Market Consensus:** The closing price is the most critical value of the day. It represents the final agreement between buyers and sellers after processing all the news and events of that session. It is the standard reference value used by institutions.
2.  **Avoiding Multicollinearity (Noise):** The four columns are highly correlated. Passing all four to an algorithm (like XGBoost or a Neural Network) does not provide four times the information; it introduces mathematical redundancy. This can confuse the model and decrease its efficiency. Keeping only the "Close" price provides a single, clean, and representative variable.

In [3]:
# --- 1. DOWNLOAD FINANCIAL DATA ---
print("Downloading Brent crude oil data...")
brent_df = yf.download('BZ=F', start='2014-12-28', end='2019-01-02')[['Close']]
brent_df.rename(columns={'Close': 'brent_close_usd'}, inplace=True)
print(f"Data from: {brent_df.index.min()}, Until: {brent_df.index.max()}\n")

print("Downloading TTF Natural Gas data...")
# TTF=F is the Dutch TTF Natural Gas Calendar. It is already priced in EUR/MWh.
ttf_df = yf.download('TTF=F', start='2014-12-30', end='2019-01-02')[['Close']]
ttf_df.rename(columns={'Close': 'ttf_gas_eur'}, inplace=True)
print(f"Data from: {ttf_df.index.min()}, Until: {ttf_df.index.max()}\n")

print("Downloading EUR/USD data...")
eurusd_df = yf.download('EURUSD=X', start='2014-12-30', end='2018-12-31')[['Close']]
eurusd_df.rename(columns={'Close': 'eurusd_close'}, inplace=True)
print(f"Data from: {eurusd_df.index.min()}, Until: {eurusd_df.index.max()}\n")

Downloading Brent crude oil data...

[*********************100%***********************]  1 of 1 completed

Data from: 2014-12-29 00:00:00, Until: 2018-12-31 00:00:00

Downloading TTF Natural Gas data...

[*********************100%***********************]  1 of 1 completed

Data from: 2017-10-23 00:00:00, Until: 2018-12-31 00:00:00

Downloading EUR/USD data...

[*********************100%***********************]  1 of 1 completed

Data from: 2014-12-30 00:00:00, Until: 2018-12-28 00:00:00

In [4]:
# --- 2. LOAD TTF FROM CSV (Investing.com) ---
df_ttf = pd.read_csv('../data/raw/dutch_ttf_eur.csv')
date_col = 'Fecha' if 'Fecha' in df_ttf.columns else 'Date'
price_col = 'Último' if 'Último' in df_ttf.columns else 'Price'

if df_ttf[price_col].dtype == 'object':
    df_ttf[price_col] = df_ttf[price_col].str.replace('.', '', regex=False)
    df_ttf[price_col] = df_ttf[price_col].str.replace(',', '.', regex=False)
    df_ttf[price_col] = df_ttf[price_col].astype(float)

df_ttf[date_col] = pd.to_datetime(df_ttf[date_col], format='mixed', dayfirst=True)
df_ttf = df_ttf.set_index(date_col).sort_index()
df_ttf = df_ttf[[price_col]].rename(columns={price_col: 'ttf_gas_eur'})

In [5]:
# --- 3. WEEKEND HANDLING & DATA LEAKAGE (DAILY NAIVE) ---
# Mantenemos las fechas sin zona horaria (naive) para que el join no falle
all_days = pd.date_range(start='2014-12-28', end='2018-12-31', freq='D')

brent_df = brent_df.reindex(all_days).ffill()
eurusd_df = eurusd_df.reindex(all_days).ffill()
df_ttf = df_ttf.reindex(all_days).ffill()

# Prevenir Data Leakage (Shift 1 día)
brent_df['brent_close_usd_lag1'] = brent_df['brent_close_usd'].shift(1)
eurusd_df['eurusd_close_lag1'] = eurusd_df['eurusd_close'].shift(1)
df_ttf['ttf_gas_eur_lag1'] = df_ttf['ttf_gas_eur'].shift(1)

# Limpiar columnas originales que miran al futuro
brent_df = brent_df.drop(columns=['brent_close_usd'])
eurusd_df = eurusd_df.drop(columns=['eurusd_close'])
df_ttf = df_ttf.drop(columns=['ttf_gas_eur'])

# --- 4. COMBINE EVERYTHING ---
# Aplanar columnas MultiIndex de yfinance
if isinstance(brent_df.columns, pd.MultiIndex):
    brent_df.columns = brent_df.columns.get_level_values(0)
if isinstance(eurusd_df.columns, pd.MultiIndex):
    eurusd_df.columns = eurusd_df.columns.get_level_values(0)

# Unimos los 3 datasets (como no tienen zona horaria, encajan a la perfección)
macro_df = brent_df.join(eurusd_df).join(df_ttf)

# Feature Engineering: Brent en Euros
macro_df['brent_close_eur_lag1'] = macro_df['brent_close_usd_lag1'] / macro_df['eurusd_close_lag1']

# Borrar filas nulas generadas por los lags al principio
macro_df = macro_df.dropna()
macro_df = macro_df.drop(columns=["brent_close_usd_lag1"])

# --- 5. TIMEZONE CONVERSION AND HOURLY EXPANSION ---
# Aplicamos la conversión Madrid -> UTC a TODO el dataframe unido
macro_df.index = macro_df.index.tz_localize('Europe/Madrid').tz_convert('UTC')

# Creamos el índice horario final objetivo
hourly_utc_idx = pd.date_range(
    start='2014-12-31 23:00:00+00:00', 
    end='2018-12-31 23:00:00+00:00', 
    freq='h'
)

# Expandimos a resolución horaria repitiendo el valor del día
macro_hourly_df = macro_df.reindex(hourly_utc_idx, method='ffill')

print("¡Dataset macroeconómico horario listo y alineado!")
display(macro_hourly_df.head(10))

¡Dataset macroeconómico horario listo y alineado!

,eurusd_close_lag1,ttf_gas_eur_lag1,brent_close_eur_lag1
2014-12-31 23:00:00+00:00,1.216205,21.296,47.138445
2015-01-01 00:00:00+00:00,1.216205,21.296,47.138445
2015-01-01 01:00:00+00:00,1.216205,21.296,47.138445
2015-01-01 02:00:00+00:00,1.216205,21.296,47.138445
2015-01-01 03:00:00+00:00,1.216205,21.296,47.138445
2015-01-01 04:00:00+00:00,1.216205,21.296,47.138445
2015-01-01 05:00:00+00:00,1.216205,21.296,47.138445
2015-01-01 06:00:00+00:00,1.216205,21.296,47.138445
2015-01-01 07:00:00+00:00,1.216205,21.296,47.138445
2015-01-01 08:00:00+00:00,1.216205,21.296,47.138445

In [6]:
macro_hourly_df.describe()

       eurusd_close_lag1  ttf_gas_eur_lag1  brent_close_eur_lag1
count       35065.000000      35065.000000          35065.000000
mean            1.132276         18.334710             49.575335
std             0.047311          3.800614              9.404097
min             1.039047         10.613000             25.547559
25%             1.096996         15.394000             43.028753
50%             1.127701         18.276000             48.561087
75%             1.166113         20.736000             55.263683
max             1.251001         29.244000             74.698665

In [7]:
(macro_hourly_df.isna()).any()

eurusd_close_lag1       False
ttf_gas_eur_lag1        False
brent_close_eur_lag1    False
dtype: bool

In [8]:
exog_columns['Economics'] = list(macro_hourly_df.columns)

# Sports

In [9]:
# 1. Read CSVs directly from the web (SP1 = Spanish First Division / La Liga)
season_urls = [
    "https://www.football-data.co.uk/mmz4281/1415/SP1.csv",
    "https://www.football-data.co.uk/mmz4281/1516/SP1.csv",
    "https://www.football-data.co.uk/mmz4281/1617/SP1.csv",
    "https://www.football-data.co.uk/mmz4281/1718/SP1.csv",
    "https://www.football-data.co.uk/mmz4281/1819/SP1.csv"
]

# Concatenate all seasons into a single DataFrame
df_list = [pd.read_csv(url, usecols=['Date', 'HomeTeam', 'AwayTeam']) for url in season_urls]
df_liga = pd.concat(df_list, ignore_index=True)

# Convert the date column (using 'mixed' and dayfirst=True to handle varying formats robustly)
df_liga['Date'] = pd.to_datetime(df_liga['Date'], format='mixed', dayfirst=True)

# 2. Define what constitutes a "Top Match"
# Filter for "El Clásico" or specific derbies

# 2.1. El Clásico (Real Madrid vs Barcelona)
is_clasico = ((df_liga['HomeTeam'] == 'Real Madrid') & (df_liga['AwayTeam'] == 'Barcelona')) | \
             ((df_liga['HomeTeam'] == 'Barcelona') & (df_liga['AwayTeam'] == 'Real Madrid'))

# 2.2. El Derbi Madrileño (Real Madrid vs Atlético de Madrid)
is_madrid_derby = ((df_liga['HomeTeam'] == 'Ath Madrid') & (df_liga['AwayTeam'] == 'Real Madrid')) | \
                  ((df_liga['HomeTeam'] == 'Real Madrid') & (df_liga['AwayTeam'] == 'Ath Madrid'))

# 2.3. El Derbi Catalán (Barcelona vs Espanyol - Note the spelling 'Espanol' in the CSV)
is_catalan_derby = ((df_liga['HomeTeam'] == 'Barcelona') & (df_liga['AwayTeam'] == 'Espanol')) | \
                   ((df_liga['HomeTeam'] == 'Espanol') & (df_liga['AwayTeam'] == 'Barcelona'))


# Juntamos todos los filtros en uno solo para sacar los días importantes
top_match_days_conditions = is_clasico | is_madrid_derby | is_catalan_derby

# Filtramos los días únicos y normalizamos la fecha (quitamos la hora)
top_match_days = df_liga[top_match_days_conditions]['Date'].dt.normalize().unique()

print(f"Found {len(top_match_days)} top matches during this period.")

# Key dates for the Spanish National Team in major tournaments (Euro 2016 and World Cup 2018)
national_team_dates = pd.to_datetime([
    '2016-06-13', '2016-06-17', '2016-06-21', '2016-06-27', # Euro 2016
    '2018-06-15', '2018-06-20', '2018-06-25', '2018-07-01'  # World Cup 2018
]).normalize()

# Extract only the date part (without the hour) from our macro_df index
# We remove the timezone (tz_localize(None)) to safely compare it with the match dates
macro_daily_dates = macro_hourly_df.index.normalize().tz_localize(None)

# Create binary feature columns
macro_hourly_df['is_top_liga_match'] = np.where(macro_daily_dates.isin(top_match_days), 1, 0)
macro_hourly_df['is_national_team_match'] = np.where(macro_daily_dates.isin(national_team_dates), 1, 0)

# View an example of when Spain played against Portugal in the 2018 World Cup
display(macro_hourly_df[(macro_hourly_df.index >= '2018-06-15 00:00:00+00:00') & 
                        (macro_hourly_df.index < '2018-06-15 03:00:00+00:00')])

Found 30 top matches during this period.

,eurusd_close_lag1,ttf_gas_eur_lag1,brent_close_eur_lag1,is_top_liga_match,is_national_team_match
2018-06-15 00:00:00+00:00,1.180777,22.488,64.313588,0,1
2018-06-15 01:00:00+00:00,1.180777,22.488,64.313588,0,1
2018-06-15 02:00:00+00:00,1.180777,22.488,64.313588,0,1

In [10]:
exog_columns['Sports'] = ['is_top_liga_match', 'is_national_team_match']

In [11]:
(macro_hourly_df.isna()).any()

eurusd_close_lag1         False
ttf_gas_eur_lag1          False
brent_close_eur_lag1      False
is_top_liga_match         False
is_national_team_match    False
dtype: bool

# Holidays

In [12]:
# First, make sure you have it installed: pip install holidays
import holidays

print("Adding Spanish national holidays...")

# 1. Initialize the Spain holidays object for the relevant years
# We include years from 2014 to 2019 to safely cover all boundaries
es_holidays = holidays.Spain(years=range(2014, 2020))

# 2. Create the binary feature for National Holidays
# We iterate over the dates in macro_daily_dates (which we already extracted for the matches)
# and check if each date exists in the es_holidays dictionary
macro_hourly_df['is_national_holiday'] = [1 if d in es_holidays else 0 for d in macro_daily_dates.date]

# Print a quick summary to verify
total_holiday_hours = macro_hourly_df['is_national_holiday'].sum()
print(f"Found {total_holiday_hours} hours corresponding to national holidays in the dataset.")

# View an example around Christmas 2015 to verify it works
display(macro_hourly_df[(macro_hourly_df.index >= '2015-12-24 22:00:00+00:00') & 
                        (macro_hourly_df.index <= '2015-12-25 03:00:00+00:00')])

Adding Spanish national holidays...
Found 840 hours corresponding to national holidays in the dataset.

,eurusd_close_lag1,ttf_gas_eur_lag1,brent_close_eur_lag1,is_top_liga_match,is_national_team_match,is_national_holiday
2015-12-24 22:00:00+00:00,1.095002,14.566,34.118647,0,0,0
2015-12-24 23:00:00+00:00,1.090917,14.457,34.732248,0,0,0
2015-12-25 00:00:00+00:00,1.090917,14.457,34.732248,0,0,1
2015-12-25 01:00:00+00:00,1.090917,14.457,34.732248,0,0,1
2015-12-25 02:00:00+00:00,1.090917,14.457,34.732248,0,0,1
2015-12-25 03:00:00+00:00,1.090917,14.457,34.732248,0,0,1

In [13]:
macro_hourly_df.head()

,eurusd_close_lag1,ttf_gas_eur_lag1,brent_close_eur_lag1,is_top_liga_match,is_national_team_match,is_national_holiday
2014-12-31 23:00:00+00:00,1.216205,21.296,47.138445,0,0,0
2015-01-01 00:00:00+00:00,1.216205,21.296,47.138445,0,0,1
2015-01-01 01:00:00+00:00,1.216205,21.296,47.138445,0,0,1
2015-01-01 02:00:00+00:00,1.216205,21.296,47.138445,0,0,1
2015-01-01 03:00:00+00:00,1.216205,21.296,47.138445,0,0,1

In [14]:
exog_columns['Holidays'] = ['is_national_holiday']

In [15]:
(macro_hourly_df.isna()).any()

eurusd_close_lag1         False
ttf_gas_eur_lag1          False
brent_close_eur_lag1      False
is_top_liga_match         False
is_national_team_match    False
is_national_holiday       False
dtype: bool

# Weather

In [16]:
def plot_series(df=None, columns=None, series=pd.Series([]),
                label=None, ylabel=None, title=None, start=0, end=None,
                marker='o', markersize=4, linestyle='-', figsize=(14, 6)):
    """
    Plots one or multiple time-series from a dataframe or a custom pandas series.
    'columns' accepts a single string or a list of strings.
    'label' accepts a single string or a list of strings matching the columns.
    'start' and 'end' accept both integer positions and UTC timestamp strings
    like '2015-01-05 11:00:00+00:00'.
    """
    def _slice(data):
        if isinstance(start, str) or isinstance(end, str):
            s = pd.Timestamp(start) if isinstance(start, str) else data.index[start]
            e = pd.Timestamp(end)   if isinstance(end, str)   else (data.index[end] if end is not None else data.index[-1])
            return data.loc[s:e]
        return data.iloc[start:end]

    # Normalize columns and labels to lists
    if isinstance(columns, str):
        columns = [columns]
    if isinstance(label, str):
        label = [label]
    if columns and label and len(label) != len(columns):
        raise ValueError(f"'label' length ({len(label)}) must match 'columns' length ({len(columns)})")

    sns.set()
    fig, ax = plt.subplots(figsize=figsize)
    ax.set_xlabel('Date', fontsize=16)

    if columns is not None:
        alpha = 0.6 if len(columns) > 1 else 1.0
        for i, col in enumerate(columns):
            lbl = label[i] if label else col
            ax.plot(_slice(df[col]), marker=marker, linestyle=linestyle,
                    markersize=markersize, label=lbl, alpha=alpha)
        ax.set_ylabel(ylabel, fontsize=16)

    if series.any():
        lbl = label[0] if label else None
        ax.plot(_slice(series), marker=marker, linestyle=linestyle,
                markersize=markersize, label=lbl)
        ax.set_ylabel(ylabel, fontsize=16)

    ax.legend(fontsize=16)
    if title:
        ax.set_title(title, fontsize=24)

    ax.grid(True)
    plt.tight_layout()
    return ax

In [17]:
# Convert to celsius para ver qué pasa (mirar si outliers)
# weather icon fuera
# weather_main y weather_description -> categorical conversion

In [18]:
df_weather = pd.read_csv('../data/raw/weather_features.csv')

In [19]:
display(df_weather.head())

display(df_weather.describe().round(2))

display(df_weather.info())

,dt_iso,city_name,temp,temp_min,temp_max,pressure,humidity,wind_speed,wind_deg,rain_1h,rain_3h,snow_3h,clouds_all,weather_id,weather_main,weather_description,weather_icon
0,2015-01-01 00:00:00+01:00,Valencia,270.475,270.475,270.475,1001,77,1,62,0.0,0.0,0.0,0,800,clear,sky is clear,01n
1,2015-01-01 01:00:00+01:00,Valencia,270.475,270.475,270.475,1001,77,1,62,0.0,0.0,0.0,0,800,clear,sky is clear,01n
2,2015-01-01 02:00:00+01:00,Valencia,269.686,269.686,269.686,1002,78,0,23,0.0,0.0,0.0,0,800,clear,sky is clear,01n
3,2015-01-01 03:00:00+01:00,Valencia,269.686,269.686,269.686,1002,78,0,23,0.0,0.0,0.0,0,800,clear,sky is clear,01n
4,2015-01-01 04:00:00+01:00,Valencia,269.686,269.686,269.686,1002,78,0,23,0.0,0.0,0.0,0,800,clear,sky is clear,01n

,temp,temp_min,temp_max,pressure,humidity,wind_speed,wind_deg,rain_1h,rain_3h,snow_3h,clouds_all,weather_id
count,178396.00,178396.00,178396.00,178396.00,178396.00,178396.00,178396.00,178396.00,178396.00,178396.00,178396.00,178396.00
mean,289.62,288.33,291.09,1069.26,68.42,2.47,166.59,0.08,0.00,0.00,25.07,759.83
std,8.03,7.96,8.61,5969.63,21.90,2.10,116.61,0.40,0.01,0.22,30.77,108.73
min,262.24,262.24,262.24,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,200.00
25%,283.67,282.48,284.65,1013.00,53.00,1.00,55.00,0.00,0.00,0.00,0.00,800.00
50%,289.15,288.15,290.15,1018.00,72.00,2.00,177.00,0.00,0.00,0.00,20.00,800.00
75%,295.15,293.73,297.15,1022.00,87.00,4.00,270.00,0.00,0.00,0.00,40.00,801.00
max,315.60,315.15,321.15,1008371.00,100.00,133.00,360.00,12.00,2.32,21.50,100.00,804.00

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178396 entries, 0 to 178395
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   dt_iso               178396 non-null  object
 1   city_name            178396 non-null  object
 2   temp                 178396 non-null  float64
 3   temp_min             178396 non-null  float64
 4   temp_max             178396 non-null  float64
 5   pressure             178396 non-null  int64
 6   humidity             178396 non-null  int64
 7   wind_speed           178396 non-null  int64
 8   wind_deg             178396 non-null  int64
 9   rain_1h              178396 non-null  float64
 10  rain_3h              178396 non-null  float64
 11  snow_3h              178396 non-null  float64
 12  clouds_all           178396 non-null  int64
 13  weather_id           178396 non-null  int64
 14  weather_main         178396 non-null  object
 15  weather_description  178396 non-null  object
 16  weather_icon         178396 non-null  object
dtypes: float64(6), int64(6), object(5)
memory usage: 23.1+ MB

None

In [20]:
df_weather[['temp', 'temp_min', 'temp_max']] -= 273.15
df_weather['wind_speed'] *= 3.6
df_weather['wind_x'] = np.cos(np.radians(df_weather['wind_deg']))
df_weather['wind_y'] = np.sin(np.radians(df_weather['wind_deg']))
df_weather = df_weather.drop(columns=["wind_deg"])

In [21]:
display(df_weather.head())

display(df_weather.describe().round(2))

display(df_weather.info())

,dt_iso,city_name,temp,temp_min,temp_max,pressure,humidity,wind_speed,rain_1h,rain_3h,snow_3h,clouds_all,weather_id,weather_main,weather_description,weather_icon,wind_x,wind_y
0,2015-01-01 00:00:00+01:00,Valencia,-2.675,-2.675,-2.675,1001,77,3.6,0.0,0.0,0.0,0,800,clear,sky is clear,01n,0.469472,0.882948
1,2015-01-01 01:00:00+01:00,Valencia,-2.675,-2.675,-2.675,1001,77,3.6,0.0,0.0,0.0,0,800,clear,sky is clear,01n,0.469472,0.882948
2,2015-01-01 02:00:00+01:00,Valencia,-3.464,-3.464,-3.464,1002,78,0.0,0.0,0.0,0.0,0,800,clear,sky is clear,01n,0.920505,0.390731
3,2015-01-01 03:00:00+01:00,Valencia,-3.464,-3.464,-3.464,1002,78,0.0,0.0,0.0,0.0,0,800,clear,sky is clear,01n,0.920505,0.390731
4,2015-01-01 04:00:00+01:00,Valencia,-3.464,-3.464,-3.464,1002,78,0.0,0.0,0.0,0.0,0,800,clear,sky is clear,01n,0.920505,0.390731

,temp,temp_min,temp_max,pressure,humidity,wind_speed,rain_1h,rain_3h,snow_3h,clouds_all,weather_id,wind_x,wind_y
count,178396.00,178396.00,178396.00,178396.00,178396.00,178396.00,178396.00,178396.00,178396.00,178396.00,178396.00,178396.00,178396.00
mean,16.47,15.18,17.94,1069.26,68.42,8.89,0.08,0.00,0.00,25.07,759.83,0.15,-0.07
std,8.03,7.96,8.61,5969.63,21.90,7.55,0.40,0.01,0.22,30.77,108.73,0.72,0.67
min,-10.91,-10.91,-10.91,0.00,0.00,0.00,0.00,0.00,0.00,0.00,200.00,-1.00,-1.00
25%,10.52,9.33,11.50,1013.00,53.00,3.60,0.00,0.00,0.00,0.00,800.00,-0.53,-0.73
50%,16.00,15.00,17.00,1018.00,72.00,7.20,0.00,0.00,0.00,20.00,800.00,0.31,0.00
75%,22.00,20.58,24.00,1022.00,87.00,14.40,0.00,0.00,0.00,40.00,801.00,0.87,0.60
max,42.45,42.00,48.00,1008371.00,100.00,478.80,12.00,2.32,21.50,100.00,804.00,1.00,1.00

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178396 entries, 0 to 178395
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   dt_iso               178396 non-null  object
 1   city_name            178396 non-null  object
 2   temp                 178396 non-null  float64
 3   temp_min             178396 non-null  float64
 4   temp_max             178396 non-null  float64
 5   pressure             178396 non-null  int64
 6   humidity             178396 non-null  int64
 7   wind_speed           178396 non-null  float64
 8   rain_1h              178396 non-null  float64
 9   rain_3h              178396 non-null  float64
 10  snow_3h              178396 non-null  float64
 11  clouds_all           178396 non-null  int64
 12  weather_id           178396 non-null  int64
 13  weather_main         178396 non-null  object
 14  weather_description  178396 non-null  object
 15  weather_icon         178396 non-null  object
 16  wind_x               178396 non-null  float64
 17  wind_y               178396 non-null  float64
dtypes: float64(9), int64(4), object(5)
memory usage: 24.5+ MB

None

In [22]:
df_weather["city_name"].unique()

array(['Valencia', 'Madrid', 'Bilbao', ' Barcelona', 'Seville'],
      dtype=object)

In [23]:
df_weather["city_name"] = df_weather["city_name"].apply(lambda x: x.strip())

In [24]:
print(df_weather["weather_main"].unique())
print(df_weather["weather_description"].unique())
print(df_weather["weather_id"].unique())

print(len(df_weather["weather_main"].unique()))
print(len(df_weather["weather_description"].unique()))
print(len(df_weather["weather_id"].unique()))

['clear' 'clouds' 'rain' 'mist' 'thunderstorm' 'drizzle' 'fog' 'smoke'
 'haze' 'snow' 'dust' 'squall']
['sky is clear' 'few clouds' 'scattered clouds' 'broken clouds'
 'overcast clouds' 'light rain' 'moderate rain' 'heavy intensity rain'
 'mist' 'heavy intensity shower rain' 'shower rain' 'very heavy rain'
 'thunderstorm with heavy rain' 'thunderstorm with light rain'
 'thunderstorm with rain' 'proximity thunderstorm' 'thunderstorm'
 'light intensity shower rain' 'light intensity drizzle' 'fog' 'drizzle'
 'smoke' 'heavy intensity drizzle' 'haze' 'proximity shower rain'
 'light intensity drizzle rain' 'light snow' 'rain and snow'
 'light rain and snow' 'snow' 'light thunderstorm' 'heavy snow' 'sleet'
 'rain and drizzle' 'shower sleet' 'light shower sleet'
 'light shower snow' 'proximity moderate rain' 'ragged shower rain'
 'sand dust whirls' 'proximity drizzle' 'dust' 'squalls']
[800 801 802 803 804 500 501 502 701 522 521 503 202 200 201 211 520 300
 741 301 711 302 721 310 600 616 615 601 210 602 611 311 612 620 531 731
 761 771]
12
43
38

In [25]:
good_weather = ['sky is clear', 'few clouds', 'scattered clouds', 'broken clouds']

mid_weather = ['overcast clouds', 'light rain', 'moderate rain', 'mist', 
               'light intensity drizzle', 'fog', 'drizzle', 'smoke', 'haze', 
               'proximity shower rain', 'light intensity drizzle rain', 
               'light intensity shower rain', 'proximity drizzle', 'dust', 
               'proximity moderate rain', 'rain and drizzle']

bad_weather = ['heavy intensity rain', 'heavy intensity shower rain', 'shower rain', 
               'very heavy rain', 'thunderstorm with heavy rain', 
               'thunderstorm with light rain', 'thunderstorm with rain', 
               'proximity thunderstorm', 'thunderstorm', 'light thunderstorm', 
               'heavy intensity drizzle', 'light snow', 'rain and snow', 
               'light rain and snow', 'snow', 'heavy snow', 'sleet', 
               'shower sleet', 'light shower sleet', 'light shower snow', 
               'ragged shower rain', 'sand dust whirls', 'squalls']

# Create a mapping dictionary
weather_mapping = {}
for w in good_weather: weather_mapping[w] = 'good'
for w in mid_weather: weather_mapping[w] = 'mid'
for w in bad_weather: weather_mapping[w] = 'bad'

print((set(good_weather) | set(mid_weather) | set(bad_weather)) == set(df_weather["weather_description"].unique()))

True

In [26]:
# Apply the mapping to a new column
df_weather['weather'] = df_weather['weather_description'].map(weather_mapping)

# Drop the old qualitative columns since we have our clean categories now
cols_to_drop = ['weather_main', 'weather_id', 'weather_description', 'weather_icon', 'rain_1h',	'rain_3h', 'snow_3h']
df_weather = df_weather.drop(columns=cols_to_drop, errors='ignore')

# Now you can easily One-Hot Encode this new simplified column!
df_weather = pd.get_dummies(df_weather, columns=['weather'])

# Convert the new boolean columns to integers (1/0)
dummy_cols = [col for col in df_weather.columns if col.startswith('weather_')]
df_weather[dummy_cols] = df_weather[dummy_cols].astype(int)

print("Weather successfully grouped and encoded!")
display(df_weather.head())

Weather successfully grouped and encoded!

,dt_iso,city_name,temp,temp_min,temp_max,pressure,humidity,wind_speed,clouds_all,wind_x,wind_y,weather_bad,weather_good,weather_mid
0,2015-01-01 00:00:00+01:00,Valencia,-2.675,-2.675,-2.675,1001,77,3.6,0,0.469472,0.882948,0,1,0
1,2015-01-01 01:00:00+01:00,Valencia,-2.675,-2.675,-2.675,1001,77,3.6,0,0.469472,0.882948,0,1,0
2,2015-01-01 02:00:00+01:00,Valencia,-3.464,-3.464,-3.464,1002,78,0.0,0,0.920505,0.390731,0,1,0
3,2015-01-01 03:00:00+01:00,Valencia,-3.464,-3.464,-3.464,1002,78,0.0,0,0.920505,0.390731,0,1,0
4,2015-01-01 04:00:00+01:00,Valencia,-3.464,-3.464,-3.464,1002,78,0.0,0,0.920505,0.390731,0,1,0

In [27]:
print("Pre-processing and removing hidden duplicates...")

# 1. Ensure dt_iso is a proper datetime object and strictly in UTC
df_weather['dt_iso'] = pd.to_datetime(df_weather['dt_iso'], utc=True)

# 2. Kill the duplicates dead. 
# We keep only the first measurement per hour per city.
df_weather = df_weather.drop_duplicates(subset=['dt_iso', 'city_name'], keep='first')

print("Pivoting the weather dataset by city...")

# 3. Pivot the dataframe (now it is safe!)
df_weather_wide = df_weather.pivot(index='dt_iso', columns='city_name')

# 4. Flatten the MultiIndex columns
# From ('temp', 'Valencia') to 'valencia_temp'
df_weather_wide.columns = [f"{city.replace(' ', '_').lower()}_{feature}" 
                           for feature, city in df_weather_wide.columns]

# 5. Rename the index to 'time' so it perfectly matches your energy dataset later
df_weather_wide.index.name = 'time'

print(f"Dataset successfully pivoted! New shape: {df_weather_wide.shape}")
display(df_weather_wide.head())

Pre-processing and removing hidden duplicates...
Pivoting the weather dataset by city...
Dataset successfully pivoted! New shape: (35064, 60)

,barcelona_temp,bilbao_temp,madrid_temp,seville_temp,valencia_temp,barcelona_temp_min,bilbao_temp_min,madrid_temp_min,seville_temp_min,valencia_temp_min,...,barcelona_weather_good,bilbao_weather_good,madrid_weather_good,seville_weather_good,valencia_weather_good,barcelona_weather_mid,bilbao_weather_mid,madrid_weather_mid,seville_weather_mid,valencia_weather_mid
time,,,,,,,,,,,,,,,,,,,,,
2014-12-31 23:00:00+00:00,8.475,-3.492687,-5.825,0.225,-2.675,8.475,-3.492687,-5.825,0.225,-2.675,...,1,1,1,1,1,0,0,0,0,0
2015-01-01 00:00:00+00:00,8.475,-3.386500,-5.825,0.225,-2.675,8.475,-3.386500,-5.825,0.225,-2.675,...,1,1,1,1,1,0,0,0,0,0
2015-01-01 01:00:00+00:00,8.136,-3.898312,-6.964,0.936,-3.464,8.136,-3.898312,-6.964,0.936,-3.464,...,1,1,1,1,1,0,0,0,0,0
2015-01-01 02:00:00+00:00,8.136,-3.946656,-6.964,0.936,-3.464,8.136,-3.946656,-6.964,0.936,-3.464,...,1,1,1,1,1,0,0,0,0,0
2015-01-01 03:00:00+00:00,8.136,-3.664500,-6.964,0.936,-3.464,8.136,-3.664500,-6.964,0.936,-3.464,...,1,1,1,1,1,0,0,0,0,0

In [28]:
for x in [x.lower() for x in df_weather['city_name'].unique()]:
    display(df_weather_wide[[f'{x}_weather_bad', f'{x}_weather_mid', f'{x}_weather_good']].sum(axis=0))
    print()

valencia_weather_bad       291
valencia_weather_mid      2283
valencia_weather_good    32490
dtype: int64

madrid_weather_bad       339
madrid_weather_mid      4223
madrid_weather_good    30502
dtype: int64

bilbao_weather_bad       778
bilbao_weather_mid      9764
bilbao_weather_good    24522
dtype: int64

barcelona_weather_bad       899
barcelona_weather_mid      3824
barcelona_weather_good    30341
dtype: int64

seville_weather_bad       304
seville_weather_mid      4456
seville_weather_good    30304
dtype: int64

In [29]:
for x in [x.lower() for x in df_weather['city_name'].unique()]:
    display(df_weather_wide[[y for y in list(df_weather_wide.columns) if y.startswith(x)]].describe().round(2))

,valencia_temp,valencia_temp_min,valencia_temp_max,valencia_pressure,valencia_humidity,valencia_wind_speed,valencia_clouds_all,valencia_wind_x,valencia_wind_y,valencia_weather_bad,valencia_weather_good,valencia_weather_mid
count,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00
mean,17.63,17.08,18.21,1015.98,65.09,9.69,20.74,0.27,-0.06,0.01,0.93,0.07
std,7.23,7.09,7.52,11.94,19.68,9.30,25.60,0.61,0.74,0.09,0.26,0.25
min,-4.32,-4.32,-4.32,969.00,8.00,0.00,0.00,-1.00,-1.00,0.00,0.00,0.00
25%,12.00,12.00,12.50,1012.00,51.00,3.60,0.00,-0.21,-0.87,0.00,1.00,0.00
50%,17.04,17.00,18.00,1017.00,67.00,7.20,20.00,0.34,0.00,0.00,1.00,0.00
75%,23.00,22.22,24.00,1021.00,82.00,14.40,20.00,0.87,0.77,0.00,1.00,0.00
max,38.00,38.00,41.67,1087.00,100.00,478.80,100.00,1.00,1.00,1.00,1.00,1.00

,madrid_temp,madrid_temp_min,madrid_temp_max,madrid_pressure,madrid_humidity,madrid_wind_speed,madrid_clouds_all,madrid_wind_x,madrid_wind_y,madrid_weather_bad,madrid_weather_good,madrid_weather_mid
count,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00
mean,15.13,13.90,16.22,1011.78,58.73,8.76,20.66,0.17,-0.07,0.01,0.87,0.12
std,9.33,9.18,9.68,20.24,24.88,7.10,29.66,0.78,0.60,0.10,0.34,0.33
min,-9.02,-9.02,-9.02,927.00,0.00,0.00,0.00,-1.00,-1.00,0.00,0.00,0.00
25%,8.00,7.00,9.00,1013.00,38.00,3.60,0.00,-0.64,-0.64,0.00,1.00,0.00
50%,13.78,12.99,15.00,1017.00,59.00,7.20,0.00,0.36,-0.00,0.00,1.00,0.00
75%,21.80,20.56,23.00,1022.00,81.00,10.80,40.00,0.98,0.34,0.00,1.00,0.00
max,40.18,39.00,43.33,1042.00,100.00,64.80,100.00,1.00,1.00,1.00,1.00,1.00

,bilbao_temp,bilbao_temp_min,bilbao_temp_max,bilbao_pressure,bilbao_humidity,bilbao_wind_speed,bilbao_clouds_all,bilbao_wind_x,bilbao_wind_y,bilbao_weather_bad,bilbao_weather_good,bilbao_weather_mid
count,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00
mean,13.29,11.84,14.94,1017.48,78.73,7.05,43.44,0.23,-0.03,0.02,0.70,0.28
std,6.80,6.82,6.99,9.82,16.71,6.73,33.74,0.74,0.63,0.15,0.46,0.45
min,-6.30,-9.00,-4.17,961.00,11.00,0.00,0.00,-1.00,-1.00,0.00,0.00,0.00
25%,8.30,7.00,10.00,1013.00,67.00,3.60,6.00,-0.50,-0.64,0.00,0.00,0.00
50%,13.02,11.70,15.00,1019.00,82.00,3.60,40.00,0.50,0.00,0.00,1.00,0.00
75%,17.89,17.00,19.36,1024.00,93.00,10.80,75.00,0.98,0.50,0.00,1.00,1.00
max,39.32,38.89,45.56,1042.00,100.00,54.00,100.00,1.00,1.00,1.00,1.00,1.00

,barcelona_temp,barcelona_temp_min,barcelona_temp_max,barcelona_pressure,barcelona_humidity,barcelona_wind_speed,barcelona_clouds_all,barcelona_wind_x,barcelona_wind_y,barcelona_weather_bad,barcelona_weather_good,barcelona_weather_mid
count,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00
mean,16.72,15.47,17.89,1287.21,73.83,10.02,22.71,0.06,-0.17,0.03,0.87,0.11
std,6.72,6.46,7.29,13463.03,17.72,7.19,27.33,0.69,0.70,0.16,0.34,0.31
min,-10.91,-10.91,-10.91,0.00,0.00,0.00,0.00,-1.00,-1.00,0.00,0.00,0.00
25%,11.56,11.00,12.00,1014.00,62.00,3.60,0.00,-0.63,-0.87,0.00,1.00,0.00
50%,16.26,15.00,17.00,1017.00,76.00,7.20,20.00,0.14,-0.34,0.00,1.00,0.00
75%,22.00,20.12,23.89,1021.00,87.00,14.40,36.00,0.77,0.50,0.00,1.00,0.00
max,36.00,34.00,42.22,1008371.00,100.00,54.00,100.00,1.00,1.00,1.00,1.00,1.00

,seville_temp,seville_temp_min,seville_temp_max,seville_pressure,seville_humidity,seville_wind_speed,seville_clouds_all,seville_wind_x,seville_wind_y,seville_weather_bad,seville_weather_good,seville_weather_mid
count,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00,35064.00
mean,20.02,18.11,22.85,1018.54,63.78,8.94,14.17,0.03,-0.04,0.01,0.86,0.13
std,8.08,8.26,9.08,6.87,22.88,6.73,26.17,0.73,0.68,0.09,0.34,0.33
min,-2.10,-4.00,-1.09,986.00,7.00,0.00,0.00,-1.00,-1.00,0.00,0.00,0.00
25%,14.18,12.00,16.00,1014.00,46.00,3.60,0.00,-0.77,-0.64,0.00,1.00,0.00
50%,19.29,17.00,22.00,1018.00,67.00,7.20,0.00,0.00,0.00,0.00,1.00,0.00
75%,25.73,23.65,30.00,1023.00,83.00,10.80,20.00,0.77,0.64,0.00,1.00,0.00
max,42.45,42.00,48.00,1090.00,100.00,54.00,100.00,1.00,1.00,1.00,1.00,1.00

In [30]:
print("Cleaning the weather dataset...")

# 1. Remove duplicates (Keep the first measurement of each hour for each city)
# df_weather = df_weather.reset_index()
df_weather_wide = df_weather_wide.drop_duplicates(keep = 'first')

for x in [x.lower() for x in df_weather['city_name'].unique()]:
    
    # 2. Outlier Treatment (Based on physical atmospheric limits)
    # Atmospheric pressure outside the normal range on Earth
    df_weather_wide.loc[df_weather_wide[f'{x}_pressure'] > 1085, f'{x}_pressure'] = np.nan
    df_weather_wide.loc[df_weather_wide[f'{x}_pressure'] < 870, f'{x}_pressure'] = np.nan

    df_weather_wide.loc[df_weather_wide[f'{x}_humidity'] < 10, f'{x}_humidity'] = np.nan

    # Absurdly high wind speed (likely sensor errors)
    df_weather_wide.loc[df_weather_wide[f'{x}_wind_speed'] > 180, f'{x}_wind_speed'] = np.nan

print("Weather dataset cleaned and outlier-free!")

Cleaning the weather dataset...
Weather dataset cleaned and outlier-free!

In [31]:
for col in df_weather_wide.columns:
    if df_weather_wide[col].isna().sum() > 0:
        print(f"{col}: {df_weather_wide[col].isna().sum()}")

barcelona_pressure: 48
seville_pressure: 1
valencia_pressure: 9
barcelona_humidity: 74
madrid_humidity: 64
seville_humidity: 16
valencia_humidity: 1
valencia_wind_speed: 3

In [32]:
# 5. Impute null values (Generated by outliers or originally missing)
df_weather_wide.interpolate(method='linear', limit_direction='forward', inplace=True)

In [33]:
for col in df_weather_wide.columns:
    if df_weather_wide[col].isna().sum() > 0:
        print(f"{col}: {df_weather_wide[col].isna().sum()}")

In [34]:
df_weather_wide.head()

,barcelona_temp,bilbao_temp,madrid_temp,seville_temp,valencia_temp,barcelona_temp_min,bilbao_temp_min,madrid_temp_min,seville_temp_min,valencia_temp_min,...,barcelona_weather_good,bilbao_weather_good,madrid_weather_good,seville_weather_good,valencia_weather_good,barcelona_weather_mid,bilbao_weather_mid,madrid_weather_mid,seville_weather_mid,valencia_weather_mid
time,,,,,,,,,,,,,,,,,,,,,
2014-12-31 23:00:00+00:00,8.475,-3.492687,-5.825,0.225,-2.675,8.475,-3.492687,-5.825,0.225,-2.675,...,1,1,1,1,1,0,0,0,0,0
2015-01-01 00:00:00+00:00,8.475,-3.386500,-5.825,0.225,-2.675,8.475,-3.386500,-5.825,0.225,-2.675,...,1,1,1,1,1,0,0,0,0,0
2015-01-01 01:00:00+00:00,8.136,-3.898312,-6.964,0.936,-3.464,8.136,-3.898312,-6.964,0.936,-3.464,...,1,1,1,1,1,0,0,0,0,0
2015-01-01 02:00:00+00:00,8.136,-3.946656,-6.964,0.936,-3.464,8.136,-3.946656,-6.964,0.936,-3.464,...,1,1,1,1,1,0,0,0,0,0
2015-01-01 03:00:00+00:00,8.136,-3.664500,-6.964,0.936,-3.464,8.136,-3.664500,-6.964,0.936,-3.464,...,1,1,1,1,1,0,0,0,0,0

In [35]:
exog_columns['Weather'] = list(df_weather_wide.columns)
with open('../data/interim/exog_columns.json', 'w', encoding='utf-8') as file:
    json.dump(exog_columns, file, indent=4, ensure_ascii=False)
    
macro_hourly_df = macro_hourly_df.join(df_weather_wide).dropna()
macro_hourly_df.index.name = 'time'
macro_hourly_df.to_csv('../data/interim/exogs_df.csv', index=True)